name: "Auto increment version"
description: "Parse and update the version of the project."
author: Kaven[kaven@wuwenkai.com]
branding:
  icon: "arrow-up"
  color: "blue"
inputs:
  dir:
    default: ""
  file:
    default: ""
  index:
    default: -1
  increment:
    default: 1
  debug:
    default: false
outputs:
  oldVersion:
    description: "The old version"
  newVersion:
    description: "The new version"
runs:
  using: "node16"
  main: "dist/index.js"
